### ISSUE TITLE
Question about Fixed `cep_order` Parameter in `MultiStageFIRFilter`

### ISSUE THREAD

**Issue by tan90xx** [sp-nitech/diffsptk#103]
https://github.com/sp-nitech/diffsptk/blob/2e5f3c069c0e00653bfaebeb88140d27acda08da/diffsptk/modules/mglsadf.py#L215
https://github.com/sp-nitech/diffsptk/blob/2e5f3c069c0e00653bfaebeb88140d27acda08da/diffsptk/modules/mglsadf.py#L135
Hello,

I noticed that the `cep_order` parameter in the `MultiStageFIRFilter` class is fixed at 199. I wanted to understand the reasoning behind this choice. Experiments with different values, such as n_fft//2 (256) and 24, didn't show a significant impact on the results.

Similar to #49, it might be beneficial to add add `n_fft` as an argument to `MultiStageFIRFilter`.

**Comment by takenori-y** [comment]
> I wanted to understand the reasoning behind this choice.

The parameter specifies the order of the cepstrum derived from the input mel-cepstrum. Since mel-cepstrum can model the spectrum more precisely at lower frequencies, the converted cepstrum should have a higher dimensionality than the mel-cepstrum to maintain an equivalent representation of the input.

The default `cep_order` value was determined based on a 48 kHz setting where the order of mel-cepstrum was set to 49. You can reduce `cep_order` if you don't observe any quality degradation in your experiments. However, decreasing `cep_order` in the test below will cause the test to fail.
https://github.com/sp-nitech/diffsptk/blob/2e5f3c069c0e00653bfaebeb88140d27acda08da/tests/test_mglsadf.py#L34


> Similar to https://github.com/sp-nitech/diffsptk/issues/49, it might be beneficial to add add n_fft as an argument to MultiStageFIRFilter.

Thank you for pointing this out. I will add the parameter, although adjustments will rarely be necessary since it is only relevant when the `gamma` parameter is changed from zero.

**Comment by tan90xx** [comment]
Got it. Thank you very much!
